### ISSUE TITLE
Implement !asCapable upon large neighbor delay

### ISSUE THREAD

**Issue by davidcemin** [AVnu/Open-AVB#114]
gPTP should be marked as not capable (asCapable = false/NULL etc) when the neighbour delay is bigger than a threshold.
The default pdelay threshold for various hardware link types is specified in IEEE Std 802.1AS-Cor1-2013 Table 11-0 "Value of neighborPropDelayThresh for various links”, in clause 11.2.2. It needs to be configurable because a user may be using a converter to fibre and the software won’t know until the administrator changes it.

**Comment by andrew-elder** [comment]
Is anyone else working on this at this time?

**Comment by davidcemin** [comment]
Andrew, you self assigned this issue to yourself. Did you work on this at all?

**Comment by andrew-elder** [comment]
On 6/15/2015 4:29 PM, David Cemin wrote:
>
> Andrew, you self assigned this issue to yourself. Did you work on this at 
> all?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AVnu/Open-AVB/issues/114#issuecomment-112198918>.
>

Not yet. I think I have to consolidate ipcspec.h first. Are you wanting to 
work on it?

-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by davidcemin** [comment]
Im first updating the status of all open issues and migrating the issues from the twiki here. so we have all the problems in one big list and not spread out on github

**Comment by davidcemin** [comment]
There is no description on this issue (and apparently I was the reporter). I would like to update it with something like:

"gPTP should be marked as not capable (asCapable = false/NULL etc) when the neighbour delay is bigger than a threshold". 

Objections ? Comments? 

Question: What would be considered a large delay here? Do we have a specific threshold or should that be configurable (through config file or initialization switch)?

**Comment by jdkoftinoff** [comment]
The default pdelay threshold for various hardware link types is specified in IEEE Std 802.1AS-Cor1-2013 Table 11-0 "Value of neighborPropDelayThresh for various links”, in clause 11.2.2. Yes it needs to be configurable because a user may be using a converter to fibre and the software won’t know until the administrator changes it.

For reference IEEE Std 802.1AS-Cor1-2013 has a number of important fixes that we all need to be aware of.

Regards,
Jeff

**Comment by andrew-elder** [comment]
David, your text looks ok to me. We go up to 4 seconds on our devices.

**Comment by davidcemin** [comment]
Thank you all ! I was just trying to make more clear what needs to be done on this task
