### ISSUE TITLE
gPTP.com.c.5.3, clock accuracy

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#130]
gPTP.com.c.5.3, clockAccuracy is 0xFE, which is not in the range 0x20-22

**Comment by davidcemin** [comment]
Requirements state accuracy must be within 250ns but also say set clockAccuracy to 0xFE if unknown.
I changed it to 0x22(250ns) and now it is ok.

**Comment by andrew-elder** [comment]
That was an easy one!
