### ISSUE TITLE
Query for using Open AVB Stack

### ISSUE THREAD

**Issue by keyurparekh1** [AVnu/Open-AVB#14]
Dear Sir,

We are using Intel I210 ethernet AVB cards to test Talker Listener functionality. We download Open AVB stack and running Simple listener and simple talker on Inter I210 cards. Now when we start transmitting Audio stream from talker we measure time at listener side for receiving each audio packets. It takes around 125 us to reach each packet at listener side. But some time we found it taker more than 1ms time to reach to listener, even in one talker and one listener scenario. 

After that we use AVB-SW from dsp4you company. When we insert switch between talker-listener than it creates more problem. Listener getting data at around 900us. So we are getting delay of 900us between each packets. 

Below I have provided link for AVB switch. 
http://www.dsp4you.com/products/avb-oem-series/avb-sw

So, I want to know that, do we need to change gptp daemon or MRPD daemon to use it with AVB-SW or I can use it straight forward with switch? 

Let me know your inputs. 

Thanks & Regards,
Keyur Parekh.

**Comment by ajolas** [comment]
Hello, everyone.
We are facing the same problem with ~1ms delays between the AVB packets. Problem present in both simple_talker and live_stream talker. Disabling the timed tx doesn't help. As I understand, there is a solution for the issue. Can anyone share the information?

**Comment by andrew-elder** [comment]
Closing this question. No further correspondence for over a year!

**Comment by zeefpt** [comment]
HI folks ,
Can you put the example you use for streaming audio/video using simple_talker and live_stream talker ?~
Im trying to use gstreamer but with not sucess..
Regards,
