### ISSUE TITLE
jack talker and listener application !

### ISSUE THREAD

**Issue by SumeetPJain** [AVnu/Open-AVB#173]
Hi,

Can anyone shed some light on how actually the jack talker and jack listener applications can be ran ?
I guess may be I have to plug in some audio source into the IN ports.
Secondly I tried using 'zynaddsubfx' application to generate audio and feed it to the 'simple_talker' client using 'QjackCtl' by using the connect options in it. But still couldn't make it work.
I am attaching a snapshot of the experiment I did. 

If anyone can elaborate over this issue ? It will be really helpful.

![screenshot from 2015-01-15 17 31 53](https://cloud.githubusercontent.com/assets/5235116/5757088/a23a9b72-9cdd-11e4-8034-f0d587809952.png)

**Comment by SumeetPJain** [comment]
And one more observation is that for 'jackd_talker', the 'igb_get_wallclock' is failing that can also be seen the above snapshot. But for 'simple_talker' app, it works fine. 
Can anyone update me regarding the same ?

Thanks,
Sumeet

**Comment by sumeet-jain-engineer** [comment]
I am now able to transfer audio packets from the talker hence closing the issue !

**Comment by grandcat** [comment]
How did you fix the problem?

**Comment by sumeet-jain-engineer** [comment]
There are some changes I made in the 'jackd_talker' application. They are:-
1) With the master package, my xmit was failing which I fixed.
2) As you can see in the above snapshot that 'Input Port' needs the data to be fed from 'Output Port' and for that you need to establish a connection between them for which I initially used 'qJackCtl' utility. Later I implemented this (establishing connection between them) using jack standardized API's in the 'jackd_talker' application itself.
After this, it worked tickety-boo !!

**Comment by davidcemin** [comment]
By reading the comments i understand that this issue can be closed. Is that right ?

**Comment by sumeet-jain-engineer** [comment]
Ya sure !
