### ISSUE TITLE
Question: Difference between master and open-avb-next

### ISSUE THREAD

**Issue by VinodTadvai** [AVnu/Open-AVB#193]
What is the difference between master and open-avb-next. Looks like open-avb-next is more active than master. Is the code in open-avb-next stable?

**Comment by andrew-elder** [comment]
The code in open-avb-next is currently stable. commits are made to open-avb-next and periodically open-avb-next is merged to master

**Comment by VinodTadvai** [comment]
Thanks for your response

**Comment by pcub** [comment]
Hello  Andrew-elder. I just compiled openavb-next. I have intel i210 NIC and two xmos daisy chain boart with 1 PC. I want to connect xmos boards with 1 PC. Please give me a suggestion for this.
Thank you.
