### ISSUE TITLE
Question: What ethernet controller cards are supported by openAVB?

### ISSUE THREAD

**Issue by VinodTadvai** [AVnu/Open-AVB#194]
Apart from I210 etherent controller card, what other ethernet cards are supported by openAVB?

I see that simple_talker is dependent on ethernet card driver (igb_avb). Is gPTP and mrpd implementation also dependent on the driver?

**Comment by andrew-elder** [comment]
Only the Intel i210 at present. We are waiting for other vendors to step up.

mrpd and gPTP under linux are not dependent on the i210.

**Comment by GuillaumeLeNost** [comment]
Are there any plans to support Intel i211 / i218 ?

**Comment by intel-ethernet** [comment]
Unless you only want to use them as a listener, not a talker…. (all Intel adapters at this point have 802.1AS / 1588 support). But the I210 is the only available model with Qav and timed transmission required for a talker application.

ekm

**Comment by MythiliR** [comment]
How to enable the Hardware Queueing (802.1 Q FQTSS)in linux kernel ? Kindly suggest me
