### ISSUE TITLE
Question: Use OpenAVB components for customer demo purposes

### ISSUE THREAD

**Issue by VinodTadvai** [AVnu/Open-AVB#202]
I am from a software services company. We will like to use openAVB components for customer demo purposes of a Ethernet AVB use case. We see the need to update some of openAVB components mainly talker and listener applications. Do you see any issue (legal or otherwise) with that?

This will be done strictly for demo purposes.

**Comment by intel-ethernet** [comment]
IMO that’s a question best left for your own legal representation.

Each of the components have a licensing statement – in general (at least for the Intel contributed content) it follows what we call BSD licensing – reference to the general terms here:
 http://opensource.org/licenses/BSD-3-Clause .

In general, I think you can use the various Open AVB components rather liberally in demos as well as products.

Of course, at the end if you feel so inclined, we always welcome contributions back – either bug fixes, feature enhancements, or new examples.

ekm
