### ISSUE TITLE
Strange dmatime ?

### ISSUE THREAD

**Issue by zhoupeng1982** [AVnu/Open-AVB#209]
Simple_talker.c is used to test dmatime, and result seems strange:
log(attime dmatime)=    104013778       887216480
log(attime dmatime)=    114013778       887216280
log(attime dmatime)=    124013778       887216080
log(attime dmatime)=    134013778       887215880
log(attime dmatime)=    144013778       887215680
log(attime dmatime)=    154013778       887215480
log(attime dmatime)=    164013778       887215280
log(attime dmatime)=    174013778       887215080
log(attime dmatime)=    184013778       887214880
log(attime dmatime)=    194013778       887214680
The attime increase every 10ms as I changed, the dmatime seems incorrect and only change a little digit.

Simple_talker.c is linked to Open-AVB-master, several lines added to log dmatime:
```c
cleanup:
		igb_clean(&igb_dev, &cleaned_packets);
		i = 0;
		while (cleaned_packets) {
			i++;
			tmp_packet = cleaned_packets;
			cleaned_packets = cleaned_packets->next;

			/* remap attime to compare to dma time */
			tmp_packet->attime -= (tmp_packet->attime / 1000000000)*1000000000;
			/* log attime and dmatime */
			printf("log(attime dmatime)=\t%d\t%d\n",
				(unsigned int)(tmp_packet->attime), (unsigned int)(tmp_packet->dmatime));

			tmp_packet->next = free_packets;
			free_packets = tmp_packet;
		}
	}
```

**Comment by zhoupeng1982** [comment]
This is a bug: if dmatime is wanted, 1588_STAT_EN must be set in TQAVCTRL, 
which is missing in kmod and lib.
When I add this flag 1588_STAT_EN, every thing is right:
log(attime dmatime)=    403080885       403073365
log(attime dmatime)=    413080885       413073221
log(attime dmatime)=    423080885       423073317
log(attime dmatime)=    433080885       433073317
log(attime dmatime)=    443080885       443073317
log(attime dmatime)=    453080885       453073237
log(attime dmatime)=    463080885       463073365
log(attime dmatime)=    473080885       473073189
log(attime dmatime)=    483080885       483073301
log(attime dmatime)=    493080885       493073189

**Comment by zhoupeng1982** [comment]
This is a bug: if dmatime is wanted, 1588_STAT_EN must be set in TQAVCTRL, 
which is missing both in kmod and lib.
When I add this flag 1588_STAT_EN, every thing is right:
log(attime dmatime)= 403080885 403073365
log(attime dmatime)= 413080885 413073221
log(attime dmatime)= 423080885 423073317
log(attime dmatime)= 433080885 433073317
log(attime dmatime)= 443080885 443073317
log(attime dmatime)= 453080885 453073237
log(attime dmatime)= 463080885 463073365
log(attime dmatime)= 473080885 473073189
log(attime dmatime)= 483080885 483073301
log(attime dmatime)= 493080885 493073189

**Comment by davidcemin** [comment]
Im not familiar with this code, but im marking it as a bug as per the comment above.

**Comment by intel-ethernet** [comment]
Somehow this thread (and several other Open-AVB posts) got moved to my ‘junk’ box …

This history of the I210’s “DMA time” is complicated. As it was originally designed, the timestamp written back would be the 1588 PTP timestamp time. However, as implemented, the value instead is the timestamp when the packet descriptor is written back to host memory. If the tx queue writeback thresholds are set to batch tx descriptor writebacks (a performance/PCIe efficiency feature) then the timestamp reported is very far removed from the time the packet was DMAed from memory, and also potentially has little correlation to the time the packet is on the physical wire.

We continue to use the feature internally to measure low-level processor/chipset/PCIe memory access latencies by disabling transmit descriptor writeback batching, setting the pre-fetch threshold to -0-, sending a stream of timed transmit packets, looking at the attime vs dmatime (subtracting off 1.8 usec of tx descriptor writeback turnaround latency), and reporting memory access times.

“Simple talker” started out as this simple test routine. It obviously has been enhanced to make it a basic AVB protocol demonstration application. ‘dmatime’ is a vestige of the internal tool still used.

Caveat emptor.

ekm

**Comment by pinealservo** [comment]
After @intel-ethernet's comment, I'm not sure this is even a bug, or what @zhoupeng1982's change was doing. I don't think we have any need for this dmatime measurement in simple-talker, but I'm going to leave it alone unless someone who knows more about the i210 wants to re-open this.
