### ISSUE TITLE
bandwidth calculation in igb

### ISSUE THREAD

**Issue by swethachallawar** [AVnu/Open-AVB#217]
Hi,

In the I210 datasheet, iIdleSlope is calculated using the following formula:
100Mbps: BW*0x7735*0.2
1000Mbps: BW*0x7735*2

where as in OpenAVB igb.c, it is being calculated as below:
class_a_idle = (u_int32_t)(class_a_percent * 0.2 * (float)linkrate + 0.5);

Can someone please help me understand why 0.5 is being added in OpenAVB implementation?

Thanks
Swetha

**Comment by intel-ethernet** [comment]
hi Swetha –

The “+ 0.5” is to round the floating point to the nearest integer value.

ekm

**Comment by swethachallawar** [comment]
Ok. Thanks for clarifying, 

Thanks
Swetha
