### ISSUE TITLE
AVB multicast address

### ISSUE THREAD

**Issue by virupaxss** [AVnu/Open-AVB#226]
Hi

When we use the multicast address instead of the a particular destination address, is this only when a multicast of the avb packets needs to be done ? 

thanks

**Comment by eric-mann** [comment]
AVB streams use multicast destination addresses (typically). As stated in the AVnu "AVB Software Interfaces and Endpoint Architecture Guidelines" document:

"IEEE Std. 802.1Q™-2011, Clause 35.2.2.83 only defines the use of multicast and locally administered addresses for stream destination addresses. Historically there was concern about multicast behavior on WLAN networks, suggesting use of locally administered unicast addresses, although AVB-compliant WLAN access points should comply with IEEE Std. 802.11aa™-2012 which addresses multicast behavior. When a unicast stream is removed, expected bridge behavior is undefined, and hence endpoints should avoid using unicast destination stream addresses for maximum compatibility."
