### ISSUE TITLE
Q-tag Priority for class A and Class B

### ISSUE THREAD

**Issue by virupaxss** [AVnu/Open-AVB#229]
Hi all 

I am seeing priority mismatch for the Class A and B traffic in the simple_talker.c and in below links 
From the below links, 
http://www.ieee802.org/1/files/public/docs2007/avb-pannell-assumptions-0907-v8.pdf
and 
http://en.wikipedia.org/wiki/IEEE_P802.1p

Qtag priority for Class A and Class B should be 5 and 4 resp. 

but in the daemons/mrpd/msrp.h its as below 
#define MSRP_SR_CLASS_A_PRIO    3
#define MSRP_SR_CLASS_B_PRIO    2

is the priority used correct , in the application ? 

Thanks

**Comment by andrew-elder** [comment]
See IEEE802.1Q, section 34.5.

In summary msrp.h has the correct (recommended) values.

On 6/4/2015 4:17 AM, virupaxss wrote:
>
> Hi all
>
> I am seeing priority mismatch for the Class A and B traffic in the 
> simple_talker.c and in below links
> >From the below links,
> http://www.ieee802.org/1/files/public/docs2007/avb-pannell-assumptions-0907-v8.pdf
> and
> http://en.wikipedia.org/wiki/IEEE_P802.1p
>
> Qtag priority for Class A and Class B should be 5 and 4 resp.
>
> but in the daemons/mrpd/msrp.h its as below
> #define MSRP_SR_CLASS_A_PRIO 3
> #define MSRP_SR_CLASS_B_PRIO 2
>
> is the priority used correct , in the application ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AVnu/Open-AVB/issues/229>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com
