### ISSUE TITLE
pc as listener and endpoint as talker setup in openavb 

### ISSUE THREAD

**Issue by pcub** [AVnu/Open-AVB#240]
I am using open-avb-next under linux with i210 NIC.

My experiment setup is xmos daisy chain as talker and computer as listener.
I used command like:
a) ./daemon_cl eth1 -L  (but program immediately switches to master)
b) ./mrpd - mvs -i eth1
c) ./simple_listener -i eth1 -f audiof1.wav
But audiof1.wav does not play by music player and its size is only 44bytes.
In simple_listener code: 
I enabled DEBUG mode.
...
#ifdef DEBUG
	fprintf(stdout,"Compiled and applied filter.\n");  // (1)
#endif
	/** loop forever and call callback-function for every received packet */
	pcap_loop(handle, -1, pcap_callback, NULL);  // (2)
#endif
...
when I execute simple_listener, program runs until (1), but does not reach on (2).

What is wrong there?

There are common setup that people working on; two pc and avb switch and openavb under linux.
But my setup is only one xmos daisy chain board as talker and one pc as listener.

How to get simple_listener work properly in my setup?
Specifically, what changes need to be done?

**Comment by pinealservo** [comment]
I think this has been discussed elsewhere, and there's not enough information here to say much. Closing.
