### ISSUE TITLE
correctionField assumes Little-endian Machine. 

### ISSUE THREAD

**Issue by davidcemin** [AVnu/Open-AVB#243]
We should be able to detect endianness set this value accordingly.
Code is here:
https://github.com/AVnu/Open-AVB/blob/open-avb-next/daemons/gptp/common/ptp_message.cpp#L522

**Comment by davidcemin** [comment]
I confess that im not sure what I wanted when I opened this issue. I think that the idea is to discuss the way we are storing information within ptp (host/network order). Currently, several internal variables are stored in network order, and changing the whole thing would have a significant cost (code/time). 

Is that what we want to do or can we accept the things the way they are today ?

**Comment by andrew-elder** [comment]
Just fix referenced code, not the whole project.
