### ISSUE TITLE
gPTP needs to handle link state changes

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#254]
Should handle link up/down and link speed change.

**Comment by davidcemin** [comment]
What is the desirable behaviour for link state changes? For example on linuxptp when the link state changes, all the FSMs are re-started. Should we do something similar for gPTP?

**Comment by andrew-elder** [comment]
Yes, I think so.

**Comment by davidcemin** [comment]
There must be other things to do on the driver level to restart things in case of a fault. With gptp running, i brought the ethernet down (ifconfig ethx down) and I started seeing some error messages. 

After killing gPTP and restarting it, I still get errors like:
Invalid TX
ERROR at 682 in ../../common/ieee1588port.cpp: Error (TX) timestamping PDelay request, error=-72	
ERROR at 1094 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response (Retrying-0), error=-72
ERROR at 1106 in ../../common/ptp_message.cpp: Error (TX) timestamping PDelay Response, error=-72

And these errors only go away if I remove the igb_avb driver and reinsert it again. Im not quite familiar with the igb driver, but is there a way of emptying any FIFOs we have and restarting clean the timestamping side after a fault ? Judging by the error, (-72 is set when reading the tx timestamp returns EAGAIN )

**Comment by davidcemin** [comment]
same happens by changing the linkspeed.

**Comment by intel-ethernet** [comment]
When you ‘down’ then ‘up’ an interface, the gPTP daemon needs to do a series of ioctl calls on the interface to re-enable the desired timestamp settings.

**Comment by davidcemin** [comment]
Could you please list the ioctl calls that need to be done in this case? We would most likely need to call these calls in case of recovering automatically from a failure... (which is the main goal of this issue)

**Comment by intel-ethernet** [comment]
I believe it is basically calling LinuxTimestamperGeneric::HWTimestamper_init() again, but Chris can confirm …

**Comment by davidcemin** [comment]
@christopher-s-hall Can you please confirm latest comment where it says that we could solve this problem by calling  LinuxTimestamperGeneric::HWTimestamper_init() ?

**Comment by davidcemin** [comment]
@kencarlino Did you guys fix this on the automotive branch already ?

**Comment by kencarlino** [comment]
@davidcemin Detecting link state changes was added to the automotive profile branch. The implementation of what happens when a state changes was only focused on the automotive profile requirements. If gPTP in general has additional requirements for what to do on a link up or link down that would need to be implemented as well.

One of the known issues mentioned in the readme is that on some platforms a phantom link up or link down event can occur at a regular interval (fairly long interval of perhaps 30 seconds). This still needs to be investigated.
