### ISSUE TITLE
Need information on gptp daemon

### ISSUE THREAD

**Issue by keyurparekh1** [AVnu/Open-AVB#266]
Hi,

I am using gptp daemon for fine method synchronization. I gone through function setMasterOffset, which internally calls driver's freq adj function. But I want to know how to calculate PPM value? And why there is fix value of INTEGRAL is 0.0024? Is there any specific reason to keep this value? Please let me know the same.

Thanks & Regards,
Keyur Parekh

**Comment by pinealservo** [comment]
If you haven't yet, you should take a look at documents/design/AVnu_gPTP_Code.asciidoc, or look at it nicely rendered by github here: 
https://github.com/AVnu/Open-AVB/blob/master/documents/design/AVnu_gPTP_Code.asciidoc

INTEGRAL and PROPORTIONAL are the tuning coefficients for the software PI controller that calculates the clock correction to synchronize/syntonize with the grand master clock. The _ppm value is the accumulated error, apparently in parts-per-million. See a primer on PID control theory for more info; I'm afraid it's not something I can adequately describe here. The code should make more sense afterward.
