### ISSUE TITLE
gPTP - auto profile, remove debugout..hpp

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#360]
Since the automotive profile feature branch adds (and uses) gptp_log.hpp, debugout.hpp should be removed.

**Comment by andrew-elder** [comment]
@kencarlino - do you agree with with change? I went to try a windows build and got lots of log output errors. During review I concluded debugout.hpp should no longer be present in the source tree.

**Comment by kencarlino** [comment]
@andrew-elder Yes I agree debugout.hpp should be phased out. That was my intention.

**Comment by andrew-elder** [comment]
This has been completed. Closing the issue.
