### ISSUE TITLE
gPTP

### ISSUE THREAD

**Issue by insanewifi** [AVnu/Open-AVB#376]
Hello 
  I am learning gPTP now. If Grandmaster is predefined and there is only one grandmaster in my the network, can I stop sending Announce message? If i dont send any Announce message will there is be any other issues for gPTP protocol stack??
Thanks in advance. .

**Comment by andrew-elder** [comment]
@insanewifi - have you read the appropriate IEEE standard(s)?

**Comment by insanewifi** [comment]
Thank you. I read the IEEE but few things are hard to understand. But i read another article which mentioned if there is only one grandmaster there is no need to be BMCA and the announce message is neither send or expected.
