### ISSUE TITLE
Not an Issue:  Echo Talker / Echo Listener (aka. avtp_pipeline) Successful Output

### ISSUE THREAD

**Issue by DMats** [AVnu/Open-AVB#397]
I just got the echo talker and echo listener examples working for the first time and wanted to post the console output here for anyone else attempting the same and who isn't sure what they're looking for.  I know something like that would have helped me early on.  This is not really an issue so I'll just close it right away.

[echo_listener_output[first_real_success].txt](https://github.com/AVnu/Open-AVB/files/263631/echo_listener_output.first_real_success.txt)
[echo_talker_output[first_real_success].txt](https://github.com/AVnu/Open-AVB/files/263630/echo_talker_output.first_real_success.txt)

EDIT: 
I had to hack avb.c to force it to connect to bus 1 instead of bus 2, so just ignore the prints:
```
this is not bus 1.  continue until we find it.
this is not bus 1.  continue until we find it.
```

**Comment by stujeffrey016** [comment]
Hi DMats,

I am facing the same problem as #382 . Can you please tell me how to fix this issue? Like which code I should rewrite or what's wrong in this situation. It seems a little roughly in #382  that I couldn't fully understand what you guys talking about.
I am using two PCs to build endpoint to endpoint as my topology. Both side use intel I210 interface and ubuntu 14.04 OS. 

Regards,
Jeffrey
