### ISSUE TITLE
pci_connect seems to be duplicated 5 times...

### ISSUE THREAD

**Issue by RikusW** [AVnu/Open-AVB#409]
While fixing #396 I discovered the duplication in the following files:

daemons/gptp/linux/src/linux_hal_i210.cpp -- not using igb_attach_tx ??
examples/jackd-talker/jackd_talker.c
examples/simple_talker/simple_talker.c
examples/common/avb.c
lib/avtp_pipeline/openavb_common/avb.c

**Comment by RikusW** [comment]
I reformatted all for easy comparison and submitted #408

**Comment by RikusW** [comment]
Should pci_connect be removed from examples/jackd-talker/jackd_talker.c and examples/simple_talker/simple_talker.c and instead use the one in examples/common/avb.c ?

**Comment by RikusW** [comment]
Reduce to 3 duplications with #416

**Comment by pinealservo** [comment]
@RikusW Do you consider this fixed now, or is there still more to do?

**Comment by RikusW** [comment]
Then avb.c/h is done, the other examples/common files can be done in a separate branch.

**Comment by pinealservo** [comment]
I finally looked at this other instance; it's using the interface for PPS configuration rather than packet handling, so it doesn't nead igb_attach_tx. It's probably not worth the effort to factor out the common code right now, so I'm going to close the issue.
