### ISSUE TITLE
Hardcode MRPD connection attributes

### ISSUE THREAD

**Issue by Tigerclaw1993** [AVnu/Open-AVB#417]
Hi,

I would like to hardcode some attributes of the mrpd connection for some tests. Attributes such as VLan-ID, Stream-ID and stream destination address, ...

So when adapting the stream reservation, I would search in msrp.c for these attributes but I can´t find the position when sending out the commands to the network. Not in msrp.c, mrpd.c or mrp.c. As far as i know the project uses a file descriptor (which I am not very familiar with) to read and write commands to the network and an local socket to communicate with local programs like listener_mrp_client which is used by the simple_listener.

My project setup consists of a Laptop using an I82579V NIC, an optional Ethernet-Switch and two AVB XMOS Boards (Another possible setup is to connect one Board and the Laptop directly). I am not using  an i210 NIC nor any AVB Switch, which seems to cause some trouble detecting automatically values for the already named attributes. The target is to build up a valid connection to one of the XMOS Boards that is acting as talker and receive its sended packages.

**Comment by andrew-elder** [comment]
Have a read of https://github.com/AVnu/Open-AVB/blob/master/examples/mrp_client/mrpValidate.c
