### ISSUE TITLE
Question:  Reliable transmission of mission critical or safety data via AVB.

### ISSUE THREAD

**Issue by DMats** [AVnu/Open-AVB#422]
Does AVB alone guarantee reliable transmission of stream data (Class A/Class B) or does it need some other protocol like TCP/IP on top to provide a retry mechanism?  Since SRP guarantees available bandwidth does that mean a retry mechanism such as the one provided by TCP/IP is not really necessary?

Additional thoughts:
In the IEEE 1722.1-2013 spec, I see that ACMP and AECP provide a retry mechanism, but I don't see anything about reliability guarantees in 1722-2011 AVTP, 802.1AS-2011 gPTP, or 802.1Q-2011 SRP/FQTSS.

From the Wikipedia article about [Packet Loss](https://en.wikipedia.org/wiki/Packet_loss) I know that most packet loss is caused by congestion - but this is solved by using SRP so perhaps a retry mechanism isn't really required.

**Comment by andrew-elder** [comment]
Correct, SRP guarantees delivery of AVTP packets, so there is no need for a retry.
