### ISSUE TITLE
open-avb-next - travis build is broken

### ISSUE THREAD

**Issue by andrew-elder** [AVnu/Open-AVB#445]
@htfujina - can you please take a look here https://travis-ci.org/AVnu/Open-AVB and review what is broken . . .

**Comment by pinealservo** [comment]
We apparently need to link with `-lrt` for `clock_gettime`.  I'll put together a quick pull request in a bit.

**Comment by andrew-elder** [comment]
Ok thanks. I'm not sure how I didn't spot this before I merged the pull request....

**Comment by pinealservo** [comment]
Pull request #446 fixes this.

**Comment by andrew-elder** [comment]
Fixed.
