### ISSUE TITLE
gPTP doesn't correctly read PHY delay adjustments from .ini file

### ISSUE THREAD

**Issue by christopher-s-hall** [AVnu/Open-AVB#456]
Changing these values in the .ini file has no effect. The output of gPTP indicates that the results were parsed correctly:

...
phy_delay_gb_tx: 7000
phy_delay_gb_rx: 7000
phy_delay_mb_tx: 7000
phy_delay_mb_rx: 7000
...

The configuration file appears to be read (in daemon_cl) after the port is already initialized.

**Comment by andrew-elder** [comment]
Is anyone working on this?

**Comment by andrew-elder** [comment]
@christopher-s-hall - I think this is fixed now, correct?

**Comment by christopher-s-hall** [comment]
No. If it's still not working correctly, I'll take a look when I have some time. It will probably be weeks before I have time.

**Comment by andrew-elder** [comment]
My bad. I thought this commit https://github.com/AVnu/Open-AVB/pull/450/commits/e884d818b9671fc4ffab0de800703e67463a056e fixed it....   Maybe I mis-understand your response? Are you saying "No it should no longer be a bug/issue"?  Or, maybe "No I haven't tested the fix"?

**Comment by christopher-s-hall** [comment]
That pull request is closed out and contains other stuff as well. If you can “cherry pick” that out then go for it.

**Comment by andrew-elder** [comment]
I would maintain that all the changes in the closed out pull request look worthwhile to me. With your permission, I'm happy to grab your changes and create new pull requests. Nothing more for you to do.

**Comment by pinealservo** [comment]
Fixed in #462
