### ISSUE TITLE
Where can we find detailed SW layout diagrams/flows to understand Open AVB?

### ISSUE THREAD

**Issue by sachindes** [AVnu/Open-AVB#480]

**Comment by pinealservo** [comment]
There are links to developer-level documentation on http://avnu.github.io/

The most comprehensive system-level documentation right now is probably contained in the avtp-pipeline documentation: http://avnu.github.io/Open-AVB/avtp-pipeline/html/sdk_overview.html#sdk_overview_architecture

The Open-AVB repository contains a variety of components from various contributors, though, and they are not all at the same level of completion or integration with one another. Some assembly is currently required to get a working system.
