### ISSUE TITLE
Runnig Gstreamer AVB plugins issue

### ISSUE THREAD

**Issue by Neha-Khan** [AVnu/Open-AVB#529]
Hello,

I'm currently trying to explore on AVB in automotive, and i'm trying to build the simple talker and listener gstreamer plugin,
i have installed plugins successfully,
currently my pc configuration is UBUNTU 16.04
and ethernet adapter details are as follows,
enp2s0 Link encap:Ethernet HWaddr 64:00:6a:45:bd:22
inet addr:192.168.7.157 Bcast:192.168.7.255 Mask:255.255.255.0
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:1373306 errors:0 dropped:0 overruns:0 frame:0
TX packets:297978 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:305475845 (305.4 MB) TX bytes:44299019 (44.2 MB)
but when i run the talker pipeline i'm getting the following issue from the pipeline, pls help me in understanding what is the issue, is there a problem regarding the configuration

gst-launch-1.0 filesrc location="test.mp4" ! avbsink interface=enp2s0
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
connect failed (No such file or directory) - are you running as root?

I'm new to the gstreamer and also to AVB please help me in resolving these issue.

**Comment by pinealservo** [comment]
I am not sure, but it may be attempting and failing to connect to the gPTP daemon shared-memory IPC interface. The author of the gstreamer examples isn't active in the project anymore, so they're largely unmaintained right now.  Please see the avtp_pipeline code for a more full-featured implementation of a gstreamer-based talker and listener.
