### ISSUE TITLE
Comunication AVB

### ISSUE THREAD

**Issue by zerbo88** [AVnu/Open-AVB#531]
hi,
is it possible comunicate beetwen Mac avb and linux open-avb ?

**Comment by davidcemin** [comment]
Hi, 

In the company that I work for, the avb stack is open-avb based. We use mainly srp from open-avb. I got my mac streaming to one of our products with a little bit of work once (some debugging on the mac side). 
That being said, ive never tried like simple talker / simple listener on a linux machine against a mac, but it is theoretically possible as far as i understand.
