### ISSUE TITLE
Open AVB stack support for Broadcom Enet PHY card

### ISSUE THREAD

**Issue by ajav88** [AVnu/Open-AVB#540]
Hi,
   We are currently implementing a simple AVB compliant system with a couple of NXP SABRE AI Boards. The boards support the Broadcom ENET PHY card (Broadr reach) which has hardware support for timestamping. Is it possible to port the open AVB stack to the NXP board with the Broadcom PHY card? The system consists of a talker and listener with a peer to peer connection as of now.

**Comment by pinealservo** [comment]
See #552
