### ISSUE TITLE
Running the live stream example without igb driver

### ISSUE THREAD

**Issue by ajav88** [AVnu/Open-AVB#544]
Hi,
   I am using an Imx6 Sabre AI board with an atheros Enet PHY card. I am able to run the gptp and the mrpd daemons. I want to run the live stream talker.c on the board but due to the absence of the igb driver I am not able to run the program. Is there any way I can edit the program to make it independent of the igb driver? My aim is to run the program on the atheros enet phy card. 

Thank you

**Comment by pinealservo** [comment]
See #552
