### ISSUE TITLE
Simple Talker Detailed Documentation

### ISSUE THREAD

**Issue by varun-v-deshpande** [AVnu/Open-AVB#547]
Hello,

Can anybody please guide me regarding where can I get detailed documentation of the program of simple talker application ?

I want to make a simple AVB Program to send packets at specific time and also I want the periodicity to be configurable. For example I want to send packet of 200B size at 10:12:24 AM with a rate of 1 packet every 10 seconds.

**Comment by pinealservo** [comment]
Sorry, we don't have any more detailed documentation on the simple_talker application.  If you can't figure out how to do what you'd like to do after spending some time reading the simple_talker code and experimenting with it, feel free to ask some more specific questions about any APIs that don't behave as you expect.
